name: Python CDK Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install npm web app dependencies
      working-directory: ./npm-vite-web-cloudfornt-s3
      run: npm ci

    - name: build npm web app
      working-directory: ./npm-vite-web-cloudfornt-s3
      run: npm run build

    - name: install AWS CDK
      run: sudo npm i -g aws-cdk

    - name: install python dependencies
      working-directory: ./cdk-cloudfront-s3
      run: pip3 install -r requirements.txt
    
    - name: CDK Synth
      working-directory: ./cdk-cloudfront-s3
      run: cdk synth

    - name: CDK Deploy
      working-directory: ./cdk-cloudfront-s3
      env: 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: cdk deploy
